
import { VocabularyItem } from '../types';

export const vocabulary: VocabularyItem[] = [
  { id: 1, term_ru: "нейронная сеть (НС)", translation_vi: "mạng nơ-ron", translation_en: "neural network (NN)" },
  { id: 2, term_ru: "сжатие без потерь", translation_vi: "nén không mất mát", translation_en: "lossless compression" },
  { id: 3, term_ru: "генетический алгоритм", translation_vi: "thuật toán di truyền", translation_en: "genetic algorithm" },
  { id: 4, term_ru: "эволюционные вычисления", translation_vi: "tính toán tiến hóa", translation_en: "evolutionary computation" },
  { id: 5, term_ru: "многокритериальная оптимизация", translation_vi: "tối ưu hóa đa mục tiêu", translation_en: "multi-objective optimization" },
  { id: 6, term_ru: "фронт Парето", translation_vi: "mặt trận Pareto", translation_en: "Pareto front" },
  { id: 7, term_ru: "теория массового обслуживания", translation_vi: "lý thuyết hàng đợi", translation_en: "queuing theory" },
  { id: 8, term_ru: "сетевая задержка", translation_vi: "độ trễ mạng", translation_en: "network latency" },
  { id: 9, term_ru: "пропускная способность", translation_vi: "băng thông / thông lượng", translation_en: "bandwidth / throughput" },
  { id: 10, term_ru: "коэффициент потерь", translation_vi: "tỷ lệ mất mát", translation_en: "loss rate" },
  { id: 11, term_ru: "проактивное прогнозирование", translation_vi: "dự báo chủ động", translation_en: "proactive forecasting" },
  { id: 12, term_ru: "упреждающее управление", translation_vi: "quản lý chủ động / phủ đầu", translation_en: "proactive management" },
  { id: 13, term_ru: "графовая нейронная сеть (GNN)", translation_vi: "mạng nơ-ron đồ thị (GNN)", translation_en: "Graph Neural Network (GNN)" },
  { id: 14, term_ru: "энтропийное кодирование", translation_vi: "mã hóa entropy", translation_en: "entropy encoding" },
  { id: 15, term_ru: "арифметическое кодирование", translation_vi: "mã hóa số học", translation_en: "arithmetic coding" },
  { id: 16, term_ru: "распределение вероятностей", translation_vi: "phân phối xác suất", translation_en: "probability distribution" },
  { id: 17, term_ru: "искусственный интеллект (ИИ)", translation_vi: "trí tuệ nhân tạo (AI)", translation_en: "Artificial Intelligence (AI)" },
  { id: 18, term_ru: "многослойный перцептрон (MLP)", translation_vi: "perceptron đa lớp (MLP)", translation_en: "Multi-Layer Perceptron (MLP)" },
  { id: 19, term_ru: "динамическая приоритизация", translation_vi: "ưu tiên hóa động", translation_en: "dynamic prioritization" },
  { id: 20, term_ru: "параметр нагрузки", translation_vi: "tham số tải", translation_en: "load parameter" },
  { id: 21, term_ru: "интенсивность входного потока", translation_vi: "cường độ luồng vào", translation_en: "input stream intensity" },
  { id: 22, term_ru: "скорость обслуживания", translation_vi: "tốc độ phục vụ", translation_en: "service rate" },
  { id: 23, term_ru: "научная задача", translation_vi: "bài toán khoa học", translation_en: "scientific problem" },
  { id: 24, term_ru: "гибридная сеть", translation_vi: "mạng lai", translation_en: "hybrid network" },
  { id: 25, term_ru: "спутниковый канал", translation_vi: "kênh vệ tinh", translation_en: "satellite channel" },
  { id: 26, term_ru: "качество обслуживания (QoS)", translation_vi: "chất lượng dịch vụ (QoS)", translation_en: "Quality of Service (QoS)" },
  { id: 27, term_ru: "стохастичность", translation_vi: "tính ngẫu nhiên", translation_en: "stochasticity" },
  { id: 28, term_ru: "математическое моделирование", translation_vi: "mô hình hóa toán học", translation_en: "mathematical modeling" },
  { id: 29, term_ru: "натурные испытания", translation_vi: "thử nghiệm thực địa", translation_en: "field tests" },
  { id: 30, term_ru: "потоковое видео", translation_vi: "video streaming", translation_en: "streaming video" },
  { id: 31, term_ru: "интерактивные данные", translation_vi: "dữ liệu tương tác", translation_en: "interactive data" },
  { id: 32, term_ru: "веб-трафик", translation_vi: "lưu lượng web", translation_en: "web traffic" },
  { id: 33, term_ru: "передача файлов", translation_vi: "truyền tệp", translation_en: "file transfer" },
  { id: 34, term_ru: "коэффициент загрузки", translation_vi: "hệ số tải", translation_en: "utilization factor" },
  { id: 35, term_ru: "ограниченный буфер", translation_vi: "bộ đệm hữu hạn", translation_en: "finite buffer" },
  { id: 36, term_ru: "многолучевая система", translation_vi: "hệ thống đa chùm", translation_en: "multibeam system" },
  { id: 37, term_ru: "энергопотребление", translation_vi: "tiêu thụ năng lượng", translation_en: "power consumption" },
  { id: 38, term_ru: "длина очереди", translation_vi: "độ dài hàng đợi", translation_en: "queue length" },
  { id: 39, term_ru: "отбор, скрещивание и мутация", translation_vi: "chọn lọc, lai ghép và đột biến", translation_en: "selection, crossover, and mutation" },
  { id: 40, term_ru: "фронт Парето", translation_vi: "mặt trận Pareto", translation_en: "Pareto front" },
  { id: 41, term_ru: "имитационное моделирование", translation_vi: "mô phỏng", translation_en: "simulation modeling" },
  { id: 42, term_ru: "пространственно-временная сеть", translation_vi: "mạng không gian-thời gian", translation_en: "spatio-temporal network" },
  { id: 43, term_ru: "адаптивное сжатие", translation_vi: "nén thích ứng", translation_en: "adaptive compression" },
  { id: 44, term_ru: "кодек", translation_vi: "bộ mã hóa-giải mã (codec)", translation_en: "codec" },
  { id: 45, term_ru: "скользящее окно", translation_vi: "cửa sổ trượt", translation_en: "sliding window" },
  { id: 46, term_ru: "извлечение признаков", translation_vi: "trích xuất đặc trưng", translation_en: "feature extraction" },
  { id: 47, term_ru: "рекуррентная нейронная сеть (RNN)", translation_vi: "mạng nơ-ron hồi quy (RNN)", translation_en: "Recurrent Neural Network (RNN)" },
  { id: 48, term_ru: "агрегация информации", translation_vi: "tổng hợp thông tin", translation_en: "information aggregation" },
  { id: 49, term_ru: "временные ряды", translation_vi: "chuỗi thời gian", translation_en: "time series" },
  { id: 50, term_ru: "время выполнения", translation_vi: "thời gian thực thi", translation_en: "execution time" },
  { id: 51, term_ru: "устойчивость к росту RTT", translation_vi: "khả năng chống chịu với sự gia tăng RTT", translation_en: "resilience to RTT growth" },
  { id: 52, term_ru: "внедрение в учебный процесс", translation_vi: "áp dụng vào quá trình giảng dạy", translation_en: "implementation in the educational process" },
  { id: 53, term_ru: "анализ чувствительности", translation_vi: "phân tích độ nhạy", translation_en: "sensitivity analysis" },
  { id: 54, term_ru: "масштабирование", translation_vi: "khả năng mở rộng", translation_en: "scalability" },
  { id: 55, term_ru: "вычислительная сложность", translation_vi: "độ phức tạp tính toán", translation_en: "computational complexity" },
  { id: 56, term_ru: "накладные расходы", translation_vi: "chi phí phát sinh / chi phí quản lý", translation_en: "overhead" },
  { id: 57, term_ru: "децентрализованный подход", translation_vi: "phương pháp phi tập trung", translation_en: "decentralized approach" },
  { id: 58, term_ru: "компоненты задержки", translation_vi: "các thành phần của độ trễ", translation_en: "latency components" },
  { id: 59, term_ru: "низкоорбитальные (LEO) системы", translation_vi: "hệ thống quỹ đạo thấp (LEO)", translation_en: "Low Earth Orbit (LEO) systems" },
  { id: 60, term_ru: "онлайн-обучение", translation_vi: "học trực tuyến", translation_en: "online learning" },
  { id: 61, term_ru: "синергетический эффект", translation_vi: "hiệu ứng cộng hưởng", translation_en: "synergistic effect" },
  { id: 62, term_ru: "логический вывод (inference)", translation_vi: "suy luận logic (inference)", translation_en: "inference" },
  { id: 63, term_ru: "джиттер", translation_vi: "jitter (biến thiên độ trễ)", translation_en: "jitter" },
  { id: 64, term_ru: "аппаратные требования", translation_vi: "yêu cầu phần cứng", translation_en: "hardware requirements" },
  { id: 65, term_ru: "замирания из-за дождя", translation_vi: "suy hao do mưa", translation_en: "rain fade" },
  { id: 66, term_ru: "квантование и прунинг", translation_vi: "lượng tử hóa và cắt tỉa", translation_en: "quantization and pruning" },
  { id: 67, term_ru: "интерпретируемость", translation_vi: "khả năng diễn giải", translation_en: "interpretability" },
  { id: 68, term_ru: "черный ящик", translation_vi: "hộp đen", translation_en: "black box" },
  { id: 69, term_ru: "механизмы внимания", translation_vi: "cơ chế chú ý", translation_en: "attention mechanisms" },
  { id: 70, term_ru: "трансферное обучение", translation_vi: "học chuyển giao", translation_en: "transfer learning" },
  { id: 71, term_ru: "дообучение (fine-tuning)", translation_vi: "tinh chỉnh (fine-tuning)", translation_en: "fine-tuning" },
  { id: 72, term_ru: "Deep Reinforcement Learning (DRL)", translation_vi: "Học tăng cường sâu (DRL)", translation_en: "Deep Reinforcement Learning (DRL)" },
  { id: 73, term_ru: "замкнутый контур управления", translation_vi: "vòng lặp điều khiển kín", translation_en: "closed control loop" },
  { id: 74, term_ru: "предел Шеннона", translation_vi: "giới hạn Shannon", translation_en: "Shannon limit" },
  { id: 75, term_ru: "робастная оптимизация", translation_vi: "tối ưu hóa bền vững", translation_en: "robust optimization" },
  { id: 76, term_ru: "кибербезопасность", translation_vi: "an ninh mạng", translation_en: "cybersecurity" },
  { id: 77, term_ru: "состязательные атаки", translation_vi: "tấn công đối nghịch", translation_en: "adversarial attacks" },
  { id: 78, term_ru: "состязательное обучение", translation_vi: "huấn luyện đối nghịch", translation_en: "adversarial training" },
  { id: 79, term_ru: "ансамбли моделей", translation_vi: "tổ hợp các mô hình", translation_en: "model ensembles" },
  { id: 80, term_ru: "стандартизация", translation_vi: "tiêu chuẩn hóa", translation_en: "standardization" },
  { id: 81, term_ru: "интерфейсы (API)", translation_vi: "giao diện (API)", translation_en: "interfaces (API)" },
  { id: 82, term_ru: "интероперабельность", translation_vi: "khả năng tương tác", translation_en: "interoperability" },
  { id: 83, term_ru: "политика сетевого оператора", translation_vi: "chính sách của nhà khai thác mạng", translation_en: "network operator policy" },
  { id: 84, term_ru: "реактивный", translation_vi: "bị động / phản ứng", translation_en: "reactive" },
  { id: 85, term_ru: "проактивный", translation_vi: "chủ động", translation_en: "proactive" },
  { id: 86, term_ru: "GEO-канал", translation_vi: "kênh GEO", translation_en: "GEO channel" },
  { id: 87, term_ru: "OFDM-канал", translation_vi: "kênh OFDM", translation_en: "OFDM channel" },
  { id: 88, term_ru: "статический", translation_vi: "tĩnh", translation_en: "static" },
  { id: 89, term_ru: "динамический", translation_vi: "động", translation_en: "dynamic" },
  { id: 90, term_ru: "аналитический инструмент", translation_vi: "công cụ phân tích", translation_en: "analytical tool" },
  { id: 91, term_ru: "предобработчик", translation_vi: "bộ tiền xử lý", translation_en: "preprocessor" },
  { id: 92, term_ru: "компромиссное решение", translation_vi: "giải pháp thỏa hiệp", translation_en: "trade-off solution" },
  { id: 93, term_ru: "недоминируемые решения", translation_vi: "các giải pháp không bị trội", translation_en: "non-dominated solutions" },
  { id: 94, term_ru: "элита (в ГА)", translation_vi: "tinh hoa (trong GA)", translation_en: "elite (in GA)" },
  { id: 95, term_ru: "узел (в графе)", translation_vi: "nút (trong đồ thị)", translation_en: "node (in a graph)" },
  { id: 96, term_ru: "ребро (в графе)", translation_vi: "cạnh (trong đồ thị)", translation_en: "edge (in a graph)" },
  { id: 97, term_ru: "прикладное значение", translation_vi: "ý nghĩa ứng dụng", translation_en: "applied significance" },
  { id: 98, term_ru: "фундаментальный", translation_vi: "cơ bản / nền tảng", translation_en: "fundamental" },
  { id: 99, term_ru: "академические вопросы", translation_vi: "câu hỏi học thuật", translation_en: "academic questions" },
  { id: 100, term_ru: "дальновидный взгляд", translation_vi: "cái nhìn sâu rộng / tầm nhìn xa", translation_en: "forward-looking view" }
]
